include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - ".dart_tool/**"
    - "packages/**/example/**"

linter:
  rules:
    # Flutter specific
    avoid_print: false
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    
    # Code style
    prefer_single_quotes: true
    always_declare_return_types: true
    prefer_typing_uninitialized_variables: true
    avoid_returning_null_for_future: true
    await_only_futures: true
    curly_braces_in_flow_control_structures: true
    
    # Maintainability
    use_super_parameters: true
    use_colored_box: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_empty: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true

# Additional exclude patterns for generated files
exclude:
  - "**/*.config.dart"
  - "**/*.mocks.dart"