import 'package:samachar_plus_ott_app/models.dart';

final List<LiveChannel> LIVE_CHANNELS = [
  // NATIONAL - HINDI
  LiveChannel(id: 'live-1', name: 'Aaj Tak', logoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0FgBSdI4TYVJyvq_QgXyb75TEeiszKJm6LQ&s', streamUrl: 'https://aajtaklive-amd.akamaized.net/hls/live/2014416/aajtak/aajtaklive/live_720p/chunks.m3u8', category: 'NATIONAL', subCategory: 'HINDI'),
  LiveChannel(id: 'live-2', name: 'ABP News', logoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTF2Y0RVCUCiSZTkvIn_O8KIVQKzIGxn8pV4Q&s', streamUrl: 'https://d2l4ar6y3mrs4k.cloudfront.net/live-streaming/abpnews-livetv/master_720.m3u8', category: 'NATIONAL', subCategory: 'HINDI'),
  LiveChannel(id: 'live-3', name: 'DD News', logoUrl: 'https://th-i.thgim.com/public/latest-news/wtrkwx/article68081322.ece/alternates/FREE_1200/DDNews.jpg', streamUrl: 'https://playhls.media.nic.in/hls/live/ddnews/ddnews.m3u8', category: 'NATIONAL', subCategory: 'HINDI'),
  LiveChannel(id: 'live-4', name: 'News18 India', logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/24/News_18_India.png', streamUrl: 'https://nw18live.cdn.jio.com/bpk-tv/News18_India_NW18_MOB/output01/News18_India_NW18_MOB-audio_98835_eng=98800-video=3724000.m3u8', category: 'NATIONAL', subCategory: 'HINDI'),
  LiveChannel(id: 'live-5', name: 'NDTV India', logoUrl: 'https://images.seeklogo.com/logo-png/46/2/ndtv-india-logo-png_seeklogo-466899.png', streamUrl: 'https://ndtvindiaelemarchana.akamaized.net/hls/live/2003679-b/ndtvindia/masterb_720p@3.m3u8', category: 'NATIONAL', subCategory: 'HINDI'),
  LiveChannel(id: 'live-6', name: 'Zee News', logoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNJxr9YJ_5R0AxpVM_xfGzpfobuyshYKPHAg&s', streamUrl: 'https://dknttpxmr0dwf.cloudfront.net/index_57.m3u8', category: 'NATIONAL', subCategory: 'HINDI'),
  LiveChannel(id: 'live-7', name: 'Zee Bharat', logoUrl: 'https://yt3.googleusercontent.com/QCKjEhgbRnhNTcPeTe5-uAYnLyf0OdDpYPZSgLufVeOi1LTygW2XIli33YXGohWphxWlAQRVCQ=s900-c-k-c0x00ffffff-no-rj', streamUrl: 'https://d1hp2yai3k4ork.cloudfront.net/index_4.m3u8', category: 'NATIONAL', subCategory: 'HINDI'),
  LiveChannel(id: 'live-8', name: 'Republic Bharat', logoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTE5yq5kFO48XWr25bAp1Y4xF-UGmg5OXJ6qQ&s', streamUrl: 'https://vg-republictvlive.akamaized.net/v1/master/611d79b11b77e2f571934fd80ca1413453772ac7/vglive-sk-275673/main.m3u8', category: 'NATIONAL', subCategory: 'HINDI'),
  LiveChannel(id: 'live-9', name: 'India TV', logoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRupx5hp2GkJ1hoFX1rc4omoTuLJeKp7_b2EO9qfJspAha-FH2-s8AKsr1wyIkPauvz8Rs&usqp=CAU', streamUrl: 'https://pl-indiatvnews.akamaized.net/out/v1/db79179b608641ceaa5a4d0dd0dca8da/index_3.m3u8', category: 'NATIONAL', subCategory: 'HINDI'),
  LiveChannel(id: 'live-10', name: 'News 24', logoUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/66/92/9d/66929dd4-5268-ad97-9b65-f7f1bfee8417/AppIcon-0-0-1x_U007epad-0-85-220.png/1200x630wa.png', streamUrl: 'https://vidcdn.vidgyor.com/news24-origin/liveabr/news24-origin/live_720p/chunks.m3u8', category: 'NATIONAL', subCategory: 'HINDI'),
  LiveChannel(id: 'live-11', name: 'TV9 Bharatvarsh', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a6/TV9_Bharatvarsh.svg/250px-TV9_Bharatvarsh.svg.png', streamUrl: 'https://dyjmyiv3bp2ez.cloudfront.net/pub-iotv9hinjzgtpe/liveabr/pub-iotv9hinjzgtpe/live_720p/chunks.m3u8', category: 'NATIONAL', subCategory: 'HINDI'),
  LiveChannel(id: 'live-46', name: 'Times Now Navbharat', logoUrl: 'https://i.ibb.co/jZPg3HXW/tn-navbharat.jpg', streamUrl: 'https://amg01448-samsungin-tinnavbharat-samsungin-ad-m8.amagi.tv/playlist/amg01448-samsungin-tinnavbharat-samsungin/playlist.m3u8', category: 'NATIONAL', subCategory: 'HINDI'),

  // NATIONAL - ENGLISH
  LiveChannel(id: 'live-12', name: 'WION', logoUrl: 'https://images.seeklogo.com/logo-png/60/2/wion-logo-png_seeklogo-605806.png', streamUrl: 'https://d7x8z4yuq42qn.cloudfront.net/index_7.m3u8', category: 'NATIONAL', subCategory: 'ENGLISH'),
  LiveChannel(id: 'live-13', name: 'India Today', logoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDY3XZpruzPEg5YPKa2o6_fFAoNhtJWq8JJw&s', streamUrl: 'https://feeds.intoday.in/hltapps/api/master.m3u8', category: 'NATIONAL', subCategory: 'ENGLISH'),
  LiveChannel(id: 'live-14', name: 'CNN News18', logoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKV89B5gUlXtUNUJ9J_1m_Ahxod9kO71XyYw&s', streamUrl: 'https://nw18live.cdn.jio.com/bpk-tv/CNN_News18_NW18_MOB/output01/CNN_News18_NW18_MOB-audio_98835_hin=98800-video=2293600.m3u8', category: 'NATIONAL', subCategory: 'ENGLISH'),
  LiveChannel(id: 'live-15', name: 'NDTV 24x7', logoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwjUVJCJlJaaUtIBnHE3njLdKcdWlcALk_tQ&s', streamUrl: 'https://ndtv24x7elemarchana.akamaized.net/hls/live/2003678-b/ndtv24x7/masterb_720p@3.m3u8', category: 'NATIONAL', subCategory: 'ENGLISH'),
  LiveChannel(id: 'live-16', name: 'Times Now', logoUrl: 'https://content.jdmagicbox.com/comp/kolkata/84/033p520084/catalogue/times-now-circus-avenue-kolkata-news-satellite-channels-9xcseqhba6.jpg', streamUrl: 'https://dztlhgid9me95.cloudfront.net/live-tv/Vidgyor/timesnow/live_720p/chunks.m3u8', category: 'NATIONAL', subCategory: 'ENGLISH'),
  LiveChannel(id: 'live-17', name: 'Republic TV', logoUrl: 'https://jiotv.catchup.cdn.jio.com/dare_images/images/Republic_TV.png', streamUrl: 'https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/2e31d831f08640ff92f65003bdc89991/index.m3u8', category: 'NATIONAL', subCategory: 'ENGLISH'),
  LiveChannel(id: 'live-18', name: 'Sansad TV', logoUrl: 'https://webcast.gov.in/assets/images/RajyaSabha.png', streamUrl: 'https://playhls.media.nic.in/live/rstv-360p/index.m3u8', category: 'NATIONAL', subCategory: 'ENGLISH'),
  LiveChannel(id: 'live-19', name: 'DD India', logoUrl: 'https://i.ibb.co/PZ9RmJmd/dd-india.jpg', streamUrl: 'https://test-yupptv.cachefly.net/120723/smil:ddindiahd.smil/chunklist_b896000.m3u8', category: 'NATIONAL', subCategory: 'ENGLISH'),

  // NATIONAL - BUSINESS
  LiveChannel(id: 'live-20', name: 'NDTV Profit', logoUrl: 'https://media.assettype.com/bloombergquint/2023-12/d55e2378-26a1-42ee-8d02-7ab53846081d/ndtv_profit.png?w=1200&h=675&auto=format%2Ccompress&fit=max&enlarge=true', streamUrl: 'https://ndtvprofit.akamaized.net/hls/live/2107404/ndtvprofit/chunklist_4.m3u8', category: 'NATIONAL', subCategory: 'BUSINESS'),
  LiveChannel(id: 'live-21', name: 'Zee Business', logoUrl: 'https://yt3.googleusercontent.com/sxHEe-On1euLaHO6gssZiJXWQpRgjy7duGBWC9qPmDEul_AfSvthGaGOc3uRZEhTUchMBEOJlp0=s900-c-k-c0x00ffffff-no-rj', streamUrl: 'https://dwby15d04agvq.cloudfront.net/index_5.m3u8', category: 'NATIONAL', subCategory: 'BUSINESS'),
  LiveChannel(id: 'live-22', name: 'CNBC AWAAZ', logoUrl: 'https://jiotvimages.cdn.jio.com/dare_images/images/CNBC_Awaaz.png', streamUrl: 'https://nw18live.cdn.jio.com/bpk-tv/CNBC_Awaaz_NW18_MOB/output01/CNBC_Awaaz_NW18_MOB-audio_98834_hin=98800-video=3724000.m3u8', category: 'NATIONAL', subCategory: 'BUSINESS'),

  // REGIONAL
  LiveChannel(id: 'live-31', name: 'NDTV Madhya Pradesh Chhattisgarh', logoUrl: 'https://yt3.googleusercontent.com/5S4SubzzRn25zCq2FNyrGjVgZhjHI536Ld41nAwMGQKvgrndOpDp8yhqKe1ZLg-y67YMYqAB=s900-c-k-c0x00ffffff-no-rj', streamUrl: 'https://ndtvregional.akamaized.net/hls/live/2102726-b/ndtvmpcg/chunklist_3.m3u8', category: 'REGIONAL', states: ['Madhya Pradesh', 'Chhattisgarh']),
  LiveChannel(id: 'live-32', name: 'NDTV Rajasthan', logoUrl: 'https://yt3.googleusercontent.com/H_G4mPfQH5xJWZgrqfOYg-fOSABfRpyErqhnV4WpV7NI3VnhJPY1mRuDZLcxwvHzLKTOXgsqYw=s900-c-k-c0x00ffffff-no-rj', streamUrl: 'https://ndtvregional.akamaized.net/hls/live/2102726-b/ndtvraj/master_1.m3u8', category: 'REGIONAL', states: ['Rajasthan']),
  LiveChannel(id: 'live-33', name: 'News18 Bihar-Jharkhand', logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/News18_Bihar_Jharkhand.png', streamUrl: '', category: 'REGIONAL', states: ['Bihar', 'Jharkhand']),
  LiveChannel(id: 'live-34', name: 'News18 Madhya Pradesh Chhattisgarh', logoUrl: 'https://yt3.googleusercontent.com/Y8aFJxC0NMZbPDFfGfRLr1ymVHgujMpnbdzUrMEv8M3KWFt7EmgCgA17T4f5AsKCKzVdK1tBhQ=s900-c-k-c0x00ffffff-no-rj', streamUrl: 'https://nw18live.cdn.jio.com/bpk-tv/News18_MP_Chhattisgarh_NW18_MOB/output01/News18_MP_Chhattisgarh_NW18_MOB-audio_98835_hin=98800-video=3724000.m3u8', category: 'REGIONAL', states: ['Madhya Pradesh', 'Chhattisgarh']),
  LiveChannel(id: 'live-35', name: 'News18 Rajasthan', logoUrl: 'https://yt3.googleusercontent.com/xIJSgMJGzG1RMformQj_mdyl0Xf9wihKmpPpTmXsVDjH2S_pp80OcITIL8HVL8ZuxsnbqtJVxzg=s160-c-k-c0x00ffffff-no-rj', streamUrl: 'https://nw18live.cdn.jio.com/bpk-tv/News18_Rajasthan_NW18_MOB/output01/News18_Rajasthan_NW18_MOB-audio_98835_hin=98800-video=3724000.m3u8', category: 'REGIONAL', states: ['Rajasthan']),
  LiveChannel(id: 'live-36', name: 'News18 Uttar Pradesh Uttarakhand', logoUrl: 'https://yt3.googleusercontent.com/qf5BdXxgdMXutHsPx7Y9QH-EFfhA-8hkHNPPbYtMfj9SQWyQxEjlq4EYUtdmn52zQ5mUwG29dg=s900-c-k-c0x00ffffff-no-rj', streamUrl: 'https://nw18live.cdn.jio.com/bpk-tv/News18_UP_Uttarakhand_NW18_MOB/output01/News18_UP_Uttarakhand_NW18_MOB-audio_98835_eng=98800-video=3724000.m3u8', category: 'REGIONAL', states: ['Uttar Pradesh', 'Uttarakhand']),
  LiveChannel(id: 'live-37', name: 'Z Bihar Jharkhand', logoUrl: 'https://yt3.googleusercontent.com/Tc7Ad0aVG60qoHUKbCu8bK9t6gRBZvSPauIDEIYhadkUHnT9r9hp-Q38aRYkkjYRgWJaHP-EbA=s900-c-k-c0x00ffffff-no-rj', streamUrl: 'https://d3vmwjy7v49lo5.cloudfront.net/index_4.m3u8', category: 'REGIONAL', states: ['Bihar', 'Jharkhand']),
  LiveChannel(id: 'live-39', name: 'Z Madhya Pradesh Chhattisgarh', logoUrl: 'https://yt3.googleusercontent.com/yTIy-oADsKUGbdR92P3exxP-2HpRNbxvQtz6En_2bJ1pyIgfw400ibfNErg0SXBsVGKAU1FCRA=s900-c-k-c0x00ffffff-no-rj', streamUrl: 'https://d1ek9hdbw9xxcw.cloudfront.net/index_4.m3u8', category: 'REGIONAL', states: ['Madhya Pradesh', 'Chhattisgarh']),
  LiveChannel(id: 'live-40', name: 'Z Rajasthan', logoUrl: 'https://yt3.googleusercontent.com/CqBwhwPCfGMMlZK1L0Sluelx6cA-RqN5nEZb2Uihy8JZupeU-12Gfyvw93o53SgOHpnBBW4xXkg=s900-c-k-c0x00ffffff-no-rj', streamUrl: 'https://vg-zeefta.akamaized.net/ptnr-yupptv/title-zeerajashthannews/v1/master/611d79b11b77e2f571934fd80ca1413453772ac7/8e864b9a-1681-41a0-99a6-387490bc5b24/main.m3u8', category: 'REGIONAL', states: ['Rajasthan']),
  LiveChannel(id: 'live-41', name: 'Z Uttar Pradesh Uttarakhand', logoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDqiaSpRM5Jl8ejnLl1H3VoNUWvWvjdo3XUw&s', streamUrl: 'https://duw35ict5q7th.cloudfront.net/index_3.m3u8', category: 'REGIONAL', states: ['Uttar Pradesh', 'Uttarakhand']),
];

final List<String> NEWS_CATEGORIES = [
  "National", "Technology", "Sports", "Entertainment", "Business"
];
